### PR TITLE
Fixed allowed values

### PR DESCRIPTION
**Pull request by beaufortfrancois**
This PR makes sure values in this spec are the same as https://www.w3.org/TR/mediaqueries-5/#mf-user-preferences.
Let me know if I'm missing some context.

@tomayac

### CODE REVIEW

**Comment by beaufortfrancois** [comment]
Ah! I've found why. https://www.w3.org/TR/mediaqueries-5/#mf-user-preferences and https://drafts.csswg.org/mediaqueries-5/mf-user-preferences.

**Comment by beaufortfrancois** [comment]
Which one shall we pick?

**Comment by tomayac** [comment]
The latest Editor’s Draft is what I used. I think this is what we should go with.

**Comment by beaufortfrancois** [comment]
Then we're good! Please review.

**Review by tomayac — APPROVED** [review]

**Pull request merged**
